stages:
  - build

variables:
  APP_PORT: 10020
  APP_MEM: 800
  APP_NAME: uw-task-center
  REGISTRY: "dev.xili.pub:5000"

# 编译
build:
  stage: build
  only:
    - main
    - master
  script:
    - mvn clean package -U -Dmaven.test.skip=true
    - APP_VERSION=`grep '<version>' pom.xml |awk -F'>' '{print $2}'|awk -F"<" '{print $1}'|head -n 1`
    - docker build --build-arg APP_NAME=${APP_NAME} -t ${REGISTRY}/${APP_NAME}:${APP_VERSION} .
    - docker push ${REGISTRY}/${APP_NAME}:${APP_VERSION}
    #- /home/gitlab-runner/bin/deploy-registry-app.sh ${REGISTRY} ${APP_NAME} ${APP_VERSION} ${APP_PORT} ${APP_MEM}
