name: build
on:
  push:
    branches: main
env:
  REGISTRY: "dev.xili.pub:5000"
  APP_NAME: uw-task-center
  APP_PORT: 10010
  APP_MEM: 800

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          git config --global user.token ${{ gitea.token }}
          git clone -q ${{gitea.server_url}}/${{ gitea.repository }}.git .
          mvn clean package -U -Dmaven.test.skip=true
          APP_VERSION=`grep '<version>' pom.xml |awk -F'>' '{print $2}'|awk -F"<" '{print $1}'|head -n 1`
          docker build --build-arg APP_NAME=${APP_NAME} -t ${REGISTRY}/${APP_NAME}:${APP_VERSION} .
          docker push ${REGISTRY}/${APP_NAME}:${APP_VERSION}
          # /home/gitea/runner/deploy/deploy-registry-app.sh ${REGISTRY} ${APP_NAME} ${APP_VERSION} ${APP_PORT} ${APP_MEM}